---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee-mqtt
  namespace: linole
  labels:
    app: zigbee-mqtt
spec:
  replicas: 1
  serviceName: zigbee-mqtt
  selector:
    matchLabels:
      app: zigbee-mqtt
  template:
    metadata:
      labels:
        app: zigbee-mqtt
    spec:
#      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node2
      containers:
        - name: zigbee-mqtt
          image: koenkk/zigbee2mqtt
          volumeMounts:
            - name: zigbee-mqtt-data
              mountPath: /app/data
            - name: ttyusb0
              mountPath: /dev/ttyUSB0
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      volumes:
        - name: ttyusb0
          hostPath:
            path: /dev/ttyUSB0
  volumeClaimTemplates:
    - metadata:
        name: zigbee-mqtt-data
        namespace: mqtt
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 50Mi